Fix/cloud unique slug
payloadcms/website pull request #186
Opened 2023-06-22 17:03 UTC by PatrikKozak

Before:

https://github.com/payloadcms/website/assets/35232443/800fe4b2-fb8e-462c-82ca-7b76641e1542

After:

https://github.com/payloadcms/website/assets/35232443/3643fccc-68f9-4fd0-9cef-460fc18c97db

2023-06-23 20:57 UTC, jacobsfletch commented
![Screenshot 2023-06-23 at 4 56 20 PM](https://github.com/payloadcms/website/assets/15735305/49476bb8-ae77-4d87-952c-52e580d65869)

We technically already know the slug is valid on that first load, because that's the team's existing slug. Can we adjust the code to account for this fact?

2023-06-26 14:15 UTC, jacobsfletch commented
> @jacobsfletch I updated the description - let me know what you think

What I actually meant here is that we don't need to perform that fetch at all. That slug is _currerntly in use_ so there's no need to validate it on first load.

2023-06-26 20:31 UTC, jacobsfletch commented on src/components/UniqueSlug/index.tsx
> +          dispatchSlugValidation({ type: 'SET_SLUG', payload: newSlug })
Setting the value in two places here is duplicative, `dispatchSlugValidation` should not contain the slug, it has it's own state unless we want to move purely to the reducer pattern

2023-06-26 20:31 UTC, jacobsfletch commented on src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/(build-settings)/client_page.tsx
> +          shouldValidate={false}
A better name here might be `validateOnInit`

2023-06-26 20:32 UTC, jacobsfletch requested changes
We need to consolidate state here. `slug` is duplicated across both the `useState` and `useReducer`.

2023-06-28 18:55 UTC, jacobsfletch commented on src/components/UniqueSlug/index.tsx
> +  const [slugValidation, dispatchSlugValidation] = React.useReducer(stateReducer, {
I want this to be renamed to `state, dispatchState`, and `userInteracted` can be a part of it

2023-06-28 18:57 UTC, jacobsfletch commented on src/app/cloud/[team-slug]/[project-slug]/(tabs)/settings/(build-settings)/client_page.tsx
> +          validateOnInit={false}
Remove this line after changing the initial value. See note below.

2023-06-28 18:58 UTC, jacobsfletch commented on src/components/UniqueSlug/index.tsx
> +  validateOnInit = true,
I don't think we should initialize this as `true`. It should be the other way around, so that components have to  _opt-in_ with `validateOnInit`

2023-06-28 18:59 UTC, jacobsfletch requested changes
Left a few comments, but could you also send in another screen capture? Gotta see all these changes in action.

2023-06-28 20:07 UTC, PatrikKozak commented
@jacobsfletch 

https://github.com/payloadcms/website/assets/35232443/2999020c-663d-47a2-9527-f98f44dee570

2023-06-30 16:46 UTC, merged